version: "3.9"

services:
  infoguard-frontend:
    build:
      context: .   # Path to your Next.js project with Dockerfile
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules with host empty dir

